import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Hero Section
    // 'hero.title1': 'Transform Your Digital',
    // 'hero.title2': 'Vision Into Reality',
    // 'hero.subtitle': 'An assistant that organizes your email, answers it, schedules your appointments and reminds you of them, and organizes your documents.',
    // 'hero.cta': 'Explore Our Services',

    // Hero Slides
    'hero.slide1.title': 'Automate your work',
    'hero.slide1.highlight': 'We created the perfect assistant for you',
    'hero.slide1.description': 'We craft innovative digital solutions that drive growth and excellence. From web to mobile, AI to marketing - we\'ve got you covered.',
    'hero.cta': 'Explore Our Services',

    'hero.slide2.title': 'Build Powerful',
    'hero.slide2.highlight': 'Web Applications',
    'hero.slide2.description': 'Create stunning, responsive websites and web apps that engage users and deliver exceptional performance across all devices.',

    'hero.slide3.title': 'Innovate With',
    'hero.slide3.highlight': 'Mobile Technology',
    'hero.slide3.description': 'Develop cutting-edge mobile applications for iOS and Android that provide seamless experiences and drive user engagement.',

    'hero.slide4.title': 'Empower Your Business',
    'hero.slide4.highlight': 'With AI Solutions',
    'hero.slide4.description': 'Leverage artificial intelligence and machine learning to automate processes, gain insights, and stay ahead of the competition.',

    'hero.slide5.title': 'Grow Your Brand',
    'hero.slide5.highlight': 'Digital Marketing',
    'hero.slide5.description': 'Reach your target audience effectively with data-driven marketing strategies that maximize ROI and brand visibility.',



    // Web Development
    'webdev.title': 'Web Development',
    'webdev.subtitle': 'We build powerful, scalable web applications that deliver exceptional user experiences and drive business results.',
    'webdev.technologies': 'Technologies We Master',

    // Mobile Development
    'mobiledev.title': 'Mobile Development',
    'mobiledev.subtitle': 'Create engaging mobile experiences that users love. We develop high-performance apps for iOS and Android platforms.',
    'mobiledev.approach': 'Our Mobile Approach',
    'mobiledev.discovery': 'Discovery',
    'mobiledev.discoveryDesc': 'Understanding your vision and defining the perfect mobile strategy.',
    'mobiledev.development': 'Development',
    'mobiledev.developmentDesc': 'Agile development with continuous feedback and iterations.',
    'mobiledev.launch': 'Launch & Scale',
    'mobiledev.launchDesc': 'Deploy to app stores and scale with ongoing support.',

    // AI Agents
    'ai.title': 'AI Agents',
    'ai.subtitle': 'Harness the power of artificial intelligence to transform your business operations and deliver intelligent solutions.',
    'ai.ready': 'Ready for the AI Revolution?',
    'ai.powered': 'Our AI agents are powered by cutting-edge technologies including GPT-4, Claude, OLLaMA, and custom-trained models tailored to your specific needs.',

    // Digital Marketing
    'marketing.title': 'Digital Marketing',
    'marketing.subtitle': 'Amplify your brand\'s reach and drive measurable growth with our comprehensive digital marketing solutions.',
    'marketing.channels': 'Our Marketing Channels',
    'marketing.why': 'Why Choose Us?',
    'marketing.campaigns': 'Successful Campaigns',
    'marketing.satisfaction': 'Client Satisfaction',
    'marketing.roi': 'Average ROI Increase',

    // Footer
    'footer.description': 'Transforming businesses through innovative digital solutions. We craft experiences that drive growth and success.',
    'footer.services': 'Services',
    'footer.contact': 'Contact',
    'footer.ourTeam': 'Our Team',
    'footer.teamDesc': 'A passionate group of developers, designers, and strategists dedicated to creating exceptional digital experiences.',
    'footer.joinTeam': 'Join Our Team',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.rights': 'All rights reserved.',

    // Features - Responsive Design
    'responsive.title': 'Responsive Design',
    'responsive.description': 'Beautiful websites that work flawlessly on all devices and screen sizes.',
    'responsive.detail1': 'Mobile-first approach ensuring perfect display on smartphones',
    'responsive.detail2': 'Tablet optimization with intuitive touch interfaces',
    'responsive.detail3': 'Desktop and large screen compatibility',
    'responsive.detail4': 'Fluid layouts that adapt to any screen size',
    'responsive.benefit1': 'Improved user experience across all devices',
    'responsive.benefit2': 'Better SEO rankings with mobile-first indexing',
    'responsive.benefit3': 'Reduced bounce rates and increased engagement',
    'responsive.benefit4': 'Cost-effective single codebase maintenance',

    // Features - Lightning Fast
    'lightning.title': 'Lightning Fast',
    'lightning.description': 'Optimized performance with cutting-edge technologies for blazing speed.',
    'lightning.detail1': 'Code splitting for faster initial load times',
    'lightning.detail2': 'Image optimization with next-gen formats',
    'lightning.detail3': 'CDN distribution for minimal latency',
    'lightning.detail4': 'Smart caching strategies for repeat visits',
    'lightning.benefit1': 'Load times under 1 second',
    'lightning.benefit2': '99+ PageSpeed scores',
    'lightning.benefit3': 'Smooth 60fps animations',
    'lightning.benefit4': '100% Core Web Vitals compliance',

    // Features - Modern UI/UX
    'modern.title': 'Modern UI/UX',
    'modern.description': 'Stunning interfaces designed with user experience at the forefront.',
    'modern.detail1': 'Clean, contemporary design aesthetics',
    'modern.detail2': 'Intuitive navigation and user flows',
    'modern.detail3': 'Accessibility standards compliance',
    'modern.detail4': 'Engaging micro-interactions and animations',
    'modern.benefit1': 'Increased user satisfaction and retention',
    'modern.benefit2': 'Higher conversion rates',
    'modern.benefit3': 'Professional brand image',
    'modern.benefit4': 'Competitive market advantage',

    // Features - Secure & Reliable
    'secure.title': 'Secure & Reliable',
    'secure.description': 'Built with security best practices and robust architecture.',
    'secure.detail1': 'SSL/TLS encryption for all data transmission',
    'secure.detail2': 'OWASP top 10 protection',
    'secure.detail3': 'Regular security audits and updates',
    'secure.detail4': '99.99% uptime guarantee',
    'secure.benefit1': 'Protection against cyber threats',
    'secure.benefit2': 'Data privacy and compliance',
    'secure.benefit3': '24/7 monitoring and support',
    'secure.benefit4': 'Business continuity assurance',

    // Mobile Features - iOS & Android
    'ios.title': 'iOS & Android',
    'ios.description': 'Native and cross-platform apps that deliver seamless experiences on both platforms.',
    'ios.detail1': 'Native iOS development with Swift and SwiftUI',
    'ios.detail2': 'Native Android development with Kotlin and Jetpack Compose',
    'ios.detail3': 'Cross-platform solutions using React Native and Flutter',
    'ios.detail4': 'Performance optimization for smooth user experiences',
    'ios.benefit1': 'Broader audience reach across platforms',
    'ios.benefit2': 'Consistent user experience on iOS and Android',
    'ios.benefit3': 'Faster development with shared codebases',
    'ios.benefit4': 'Easier maintenance and updates',

    // Mobile Features - Tablet Optimized
    'tablet.title': 'Tablet Optimized',
    'tablet.description': 'Fully optimized interfaces for tablets with intuitive touch interactions.',
    'tablet.detail1': 'Adaptive layouts for various tablet sizes',
    'tablet.detail2': 'Enhanced multi-touch gestures and interactions',
    'tablet.detail3': 'Split-view and multi-window support',
    'tablet.detail4': 'Optimized for both portrait and landscape modes',
    'tablet.benefit1': 'Improved productivity on larger screens',
    'tablet.benefit2': 'Better content consumption experience',
    'tablet.benefit3': 'Professional-grade business applications',
    'tablet.benefit4': 'Enhanced user engagement on tablets',

    // Mobile Features - Wearables
    'wearables.title': 'Wearables',
    'wearables.description': 'Extend your app ecosystem to smartwatches and wearable devices.',
    'wearables.detail1': 'Apple Watch and WatchOS integration',
    'wearables.detail2': 'Wear OS by Google support',
    'wearables.detail3': 'Health and fitness tracking capabilities',
    'wearables.detail4': 'Quick actions and notifications',
    'wearables.benefit1': 'Increased user engagement through wearables',
    'wearables.benefit2': 'Expanded app ecosystem',
    'wearables.benefit3': 'Access to health and fitness data',
    'wearables.benefit4': 'Innovative user experiences',

    // Mobile Features - Offline-First
    'offline.title': 'Offline-First',
    'offline.description': 'Apps that work flawlessly even without an internet connection.',
    'offline.detail1': 'Local data storage and caching',
    'offline.detail2': 'Background synchronization when online',
    'offline.detail3': 'Conflict resolution strategies',
    'offline.detail4': 'Progressive Web App (PWA) capabilities',
    'offline.benefit1': 'Improved user experience without internet',
    'offline.benefit2': 'Data synchronization when back online',
    'offline.benefit3': 'Reduced data usage',
    'offline.benefit4': 'Increased app reliability',

    // AI Features - Intelligent Automation
    'automation.title': 'Intelligent Automation',
    'automation.description': 'Automate complex workflows with AI-powered agents that learn and adapt to your business needs.',
    'automation.detail1': 'Workflow automation with AI decision-making',
    'automation.detail2': 'Process optimization and efficiency gains',
    'automation.detail3': 'Integration with existing business systems',
    'automation.detail4': 'Continuous learning and improvement',
    'automation.benefit1': 'Reduced operational costs',
    'automation.benefit2': 'Faster task completion',
    'automation.benefit3': 'Minimized human errors',
    'automation.benefit4': 'Scalable business processes',

    // AI Features - Machine Learning
    'ml.title': 'Machine Learning',
    'ml.description': 'Leverage advanced ML models to extract insights and make data-driven decisions.',
    'ml.detail1': 'Custom ML model development',
    'ml.detail2': 'Predictive analytics and forecasting',
    'ml.detail3': 'Pattern recognition and anomaly detection',
    'ml.detail4': 'Natural language processing',
    'ml.benefit1': 'Data-driven decision making',
    'ml.benefit2': 'Improved accuracy over time',
    'ml.benefit3': 'Competitive market insights',
    'ml.benefit4': 'Automated pattern discovery',

    // AI Features - Conversational AI
    'conversational.title': 'Conversational AI',
    'conversational.description': 'Build sophisticated chatbots and virtual assistants that understand natural language.',
    'conversational.detail1': 'Natural language understanding (NLU)',
    'conversational.detail2': 'Context-aware conversations',
    'conversational.detail3': 'Multi-language support',
    'conversational.detail4': 'Integration with messaging platforms',
    'conversational.benefit1': '24/7 customer support',
    'conversational.benefit2': 'Reduced support costs',
    'conversational.benefit3': 'Improved customer satisfaction',
    'conversational.benefit4': 'Scalable customer interactions',

    // AI Features - Predictive Analytics
    'predictive.title': 'Predictive Analytics',
    'predictive.description': 'Forecast trends and outcomes with AI models trained on your data.',
    'predictive.detail1': 'Time series forecasting',
    'predictive.detail2': 'Customer behavior prediction',
    'predictive.detail3': 'Risk assessment and mitigation',
    'predictive.detail4': 'Sales and revenue forecasting',
    'predictive.benefit1': 'Proactive business planning',
    'predictive.benefit2': 'Reduced business risks',
    'predictive.benefit3': 'Optimized resource allocation',
    'predictive.benefit4': 'Improved strategic decisions',

    // Marketing Features - Strategic Planning
    'strategic.title': 'Strategic Planning',
    'strategic.description': 'Comprehensive marketing strategies tailored to your business goals and target audience.',
    'strategic.detail1': 'Market research and competitor analysis',
    'strategic.detail2': 'Target audience identification',
    'strategic.detail3': 'Multi-channel campaign planning',
    'strategic.detail4': 'Budget allocation and optimization',
    'strategic.benefit1': 'Clear marketing roadmap',
    'strategic.benefit2': 'Aligned with business goals',
    'strategic.benefit3': 'Measurable objectives',
    'strategic.benefit4': 'Competitive advantage',

    // Marketing Features - SEO & SEM
    'seo.title': 'SEO & SEM',
    'seo.description': 'Optimize your online presence and drive qualified traffic to your digital properties.',
    'seo.detail1': 'Keyword research and optimization',
    'seo.detail2': 'Technical SEO improvements',
    'seo.detail3': 'Pay-per-click campaign management',
    'seo.detail4': 'Local search optimization',
    'seo.benefit1': 'Higher search engine rankings',
    'seo.benefit2': 'Increased organic traffic',
    'seo.benefit3': 'Better ROI on ad spend',
    'seo.benefit4': 'Enhanced online visibility',

    // Marketing Features - Analytics & Insights
    'analytics.title': 'Analytics & Insights',
    'analytics.description': 'Data-driven insights to measure ROI and optimize your marketing campaigns.',
    'analytics.detail1': 'Comprehensive analytics dashboards',
    'analytics.detail2': 'Conversion tracking and attribution',
    'analytics.detail3': 'A/B testing and experimentation',
    'analytics.detail4': 'Custom reporting and visualization',
    'analytics.benefit1': 'Informed decision making',
    'analytics.benefit2': 'Campaign performance optimization',
    'analytics.benefit3': 'Clear ROI measurement',
    'analytics.benefit4': 'Continuous improvement',

    // Marketing Features - Email Marketing
    'email.title': 'Email Marketing',
    'email.description': 'Engage your audience with personalized email campaigns that convert.',
    'email.detail1': 'Segmentation and personalization',
    'email.detail2': 'Automated email sequences',
    'email.detail3': 'A/B testing for email optimization',
    'email.detail4': 'Performance tracking and analytics',
    'email.benefit1': 'Higher open and click rates',
    'email.benefit2': 'Improved customer retention',
    'email.benefit3': 'Cost-effective marketing channel',
    'email.benefit4': 'Measurable campaign results',

    // Common
    'close': 'Close',
    'learnMore': 'Learn More',
    'keyFeatures': 'Key Features',
    'benefits': 'Benefits',
    'requestInfo': 'Request Information',

    // Contact Form
    'contactForm.title': 'Request Information',
    'contactForm.firstName': 'First Name',
    'contactForm.lastName': 'Last Name',
    'contactForm.email': 'Email',
    'contactForm.phone': 'Phone',
    'contactForm.feature': 'Feature of Interest',
    'contactForm.selectFeature': 'Select a feature',
    'contactForm.message': 'Message (Optional)',
    'contactForm.submit': 'Submit Request',
    'contactForm.sending': 'Sending...',
    'contactForm.success': 'Thank you! We will contact you soon.',
    'contactForm.error': 'Please complete the captcha verification.',
    'contactForm.required': 'This field is required',
    'contactForm.captcha': 'Verification: What is',

    // Privacy Policy
    'privacy.title': 'Privacy Policy',
    'privacy.effectiveDate': 'Effective Date: December 1, 2025',
    'privacy.backHome': 'Back to Home',
    'privacy.section1.title': 'Introduction',
    'privacy.section1.content': 'Autobotec.net ("we," "us," "our," or "Company") respects your privacy and is committed to protecting your personal data. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website and use our services.',
    'privacy.section2.title': 'Information We Collect',
    'privacy.section2.intro': 'We may collect information about you in a variety of ways. The information we may collect on the Site includes:',
    'privacy.section2.personalData': 'Personal Data',
    'privacy.section2.item1': 'Name and email address',
    'privacy.section2.item2': 'Phone number',
    'privacy.section2.item3': 'Company name and industry',
    'privacy.section2.item4': 'Postal address',
    'privacy.section2.item5': 'Payment information (processed securely)',
    'privacy.section2.automatic': 'Automatic Data Collection',
    'privacy.section2.item6': 'Browser type and version',
    'privacy.section2.item7': 'Operating system',
    'privacy.section2.item8': 'Pages visited and time spent on pages',
    'privacy.section2.item9': 'IP address',
    'privacy.section2.item10': 'Cookies and similar tracking technologies',
    'privacy.section3.title': 'Use of Your Information',
    'privacy.section3.intro': 'Having accurate information about you permits us to provide you with a smooth, efficient, and customized experience. Specifically, we may use information collected about you via the Site to:',
    'privacy.section3.item1': 'Process your transactions and send related information',
    'privacy.section3.item2': 'Email you regarding your account or order',
    'privacy.section3.item3': 'Fulfill and manage purchases, orders, payments, and other transactions related to the Site',
    'privacy.section3.item4': 'Generate a personal profile about you for market research purposes',
    'privacy.section3.item5': 'Increase the efficiency and operation of the Site',
    'privacy.section3.item6': 'Monitor and analyze usage and trends to improve your experience with the Site',
    'privacy.section3.item7': 'Notify you of updates to the Site',
    'privacy.section3.item8': 'Offer new products, services, or promotions',
    'privacy.section4.title': 'Disclosure of Your Information',
    'privacy.section4.intro': 'We may share information we have collected about you in certain situations:',
    'privacy.section4.item1': 'By Law or to Protect Rights: If we believe the release of information is necessary to comply with the law, enforce our Site policies, or protect ours or others\' rights, property, or safety.',
    'privacy.section4.item2': 'Third-Party Service Providers: We may share your information with third parties that perform services for us, including payment processing, data analysis, email delivery, and customer service.',
    'privacy.section4.item3': 'Business Transfers: If the Company is involved in a merger, acquisition, or sale of assets, your information may be transferred as part of that transaction.',
    'privacy.section5.title': 'Security of Your Information',
    'privacy.section5.content': 'We use administrative, technical, and physical security measures to protect your personal information. However, no method of transmission over the Internet or method of electronic storage is completely secure. While we strive to use commercially acceptable means to protect your personal information, we cannot guarantee its absolute security.',
    'privacy.section6.title': 'Contact Us',
    'privacy.section6.intro': 'If you have questions or comments about this Privacy Policy, please contact us at:',
    'privacy.contact.company': 'Autobotec.net',
    'privacy.contact.email': 'Email: ',
    'privacy.contact.phone': 'Phone: ',
    'privacy.contact.address': 'Address: 37-09 75 St, Jackson Heights, NY 11372, USA',
    'privacy.lastUpdated': 'Last Updated: December 1, 2025',

    // Terms of Service
    'terms.title': 'Terms of Service',
    'terms.effectiveDate': 'Effective Date: December 1, 2025',
    'terms.backHome': 'Back to Home',
    'terms.section1.title': 'Agreement to Terms',
    'terms.section1.para1': 'By accessing and using this website (the "Site") and services provided by Autobotec.net ("Company," "we," "us," or "our"), you accept and agree to be bound by and abide by the terms and conditions of this agreement.',
    'terms.section1.para2': 'If you do not agree to abide by the above, please do not use this service.',
    'terms.section2.title': 'Use License',
    'terms.section2.intro': 'Permission is granted to temporarily download one copy of the materials (information or software) on the Site for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:',
    'terms.section2.item1': 'Modifying or copying the materials',
    'terms.section2.item2': 'Using the materials for any commercial purpose or for any public display',
    'terms.section2.item3': 'Attempting to decompile, reverse engineer, or disassemble any software contained on the Site',
    'terms.section2.item4': 'Removing any copyright or other proprietary notations from the materials',
    'terms.section2.item5': 'Transferring the materials to another person or "mirroring" the materials on any other server',
    'terms.section2.item6': 'Violating any applicable laws or regulations related to access to the Site',
    'terms.section2.item7': 'Accessing or searching the Site by any means other than the Site\'s publicly supported interfaces',
    'terms.section3.title': 'Disclaimer',
    'terms.section3.para1': 'The materials on the Site are provided on an \'as is\' basis. The Company makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.',
    'terms.section3.para2': 'Further, the Company does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on the Site or otherwise relating to such materials or on any sites linked to the Site.',
    'terms.section4.title': 'Limitations',
    'terms.section4.content': 'In no event shall Autobotec.net or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on the Site, even if the Company or a Company authorized representative has been notified orally or in writing of the possibility of such damage.',
    'terms.section5.title': 'Accuracy of Materials',
    'terms.section5.content': 'The materials appearing on the Site could include technical, typographical, or photographic errors. The Company does not warrant that any of the materials on the Site are accurate, complete, or current. The Company may make changes to the materials contained on the Site at any time without notice.',
    'terms.section6.title': 'Links',
    'terms.section6.content': 'The Company has not reviewed all of the sites linked to its Site and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by the Company of the site. Use of any such linked website is at the user\'s own risk.',
    'terms.section7.title': 'Modifications',
    'terms.section7.content': 'The Company may revise these terms of service for the Site at any time without notice. By using this Site, you are agreeing to be bound by the then current version of these terms of service.',
    'terms.section8.title': 'Governing Law',
    'terms.section8.content': 'These terms and conditions are governed by and construed in accordance with the laws of the United States of America, and you irrevocably submit to the exclusive jurisdiction of the courts in that location.',
    'terms.section9.title': 'User Responsibilities',
    'terms.section9.intro': 'You agree to not use the Site or its content:',
    'terms.section9.item1': 'For any unlawful purpose or to solicit others to commit unlawful acts',
    'terms.section9.item2': 'To violate any international, federal, provincial, or state regulations, rules, laws, or local ordinances',
    'terms.section9.item3': 'To infringe upon or violate our intellectual property rights or the intellectual property rights of others',
    'terms.section9.item4': 'To harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability',
    'terms.section9.item5': 'To submit false or misleading information',
    'terms.section9.item6': 'To upload viruses or other malicious code or otherwise compromise the security of the Site',
    'terms.section10.title': 'Contact Us',
    'terms.section10.intro': 'If you have any questions about these Terms of Service, please contact us at:',
    'terms.contact.company': 'Autobotec.net',
    'terms.contact.email': 'Email: ',
    'terms.contact.phone': 'Phone: ',
    'terms.contact.address': 'Address: 37-09 75 St, Jackson Heights, NY 11372, USA',
    'terms.lastUpdated': 'Last Updated: December 1, 2025',
  },
  es: {
    // Hero Section
    // 'hero.title1': 'Transforma Tu Visión',
    // 'hero.title2': 'Digital En Realidad',
    // 'hero.subtitle': 'Creamos soluciones digitales innovadoras que impulsan el crecimiento y la excelencia. Desde web hasta móvil, IA hasta marketing - te tenemos cubierto.',
    // 'hero.cta': 'Explora Nuestros Servicios',

    // Hero Slides
    'hero.slide1.title': 'Transforma Tu',
    'hero.slide1.highlight': 'Visión Digital',
    'hero.slide1.description': 'Creamos soluciones digitales innovadoras que impulsan el crecimiento y la excelencia. Desde web hasta móvil, IA hasta marketing - te tenemos cubierto.',
    'hero.cta': 'Explora Nuestros Servicios',

    'hero.slide2.title': 'Construye Poderosas',
    'hero.slide2.highlight': 'Aplicaciones Web',
    'hero.slide2.description': 'Crea sitios web y aplicaciones impresionantes y responsivas que cautivan usuarios y ofrecen rendimiento excepcional en todos los dispositivos.',

    'hero.slide3.title': 'Innova Con',
    'hero.slide3.highlight': 'Tecnología Móvil',
    'hero.slide3.description': 'Desarrolla aplicaciones móviles de vanguardia para iOS y Android que proporcionan experiencias fluidas e impulsan el engagement de usuarios.',

    'hero.slide4.title': 'Potencia Tu Negocio',
    'hero.slide4.highlight': 'Con Soluciones IA',
    'hero.slide4.description': 'Aprovecha la inteligencia artificial y el aprendizaje automático para automatizar procesos, obtener insights y mantenerte adelante de la competencia.',

    'hero.slide5.title': 'Haz Crecer Tu Marca',
    'hero.slide5.highlight': 'Marketing Digital',
    'hero.slide5.description': 'Alcanza tu audiencia objetivo efectivamente con estrategias de marketing basadas en datos que maximizan el ROI y la visibilidad de marca.',

    // Web Development
    'webdev.title': 'Desarrollo Web',
    'webdev.subtitle': 'Construimos aplicaciones web potentes y escalables que ofrecen experiencias de usuario excepcionales e impulsan resultados empresariales.',
    'webdev.technologies': 'Tecnologías que Dominamos',

    // Mobile Development
    'mobiledev.title': 'Desarrollo Móvil',
    'mobiledev.subtitle': 'Crea experiencias móviles atractivas que los usuarios aman. Desarrollamos aplicaciones de alto rendimiento para plataformas iOS y Android.',
    'mobiledev.approach': 'Nuestro Enfoque Móvil',
    'mobiledev.discovery': 'Descubrimiento',
    'mobiledev.discoveryDesc': 'Comprendiendo tu visión y definiendo la estrategia móvil perfecta.',
    'mobiledev.development': 'Desarrollo',
    'mobiledev.developmentDesc': 'Desarrollo ágil con retroalimentación e iteraciones continuas.',
    'mobiledev.launch': 'Lanzamiento y Escalado',
    'mobiledev.launchDesc': 'Despliegue en tiendas de aplicaciones y escalado con soporte continuo.',

    // AI Agents
    'ai.title': 'Agentes IA',
    'ai.subtitle': 'Aprovecha el poder de la inteligencia artificial para transformar las operaciones de tu negocio y entregar soluciones inteligentes.',
    'ai.ready': '¿Listo para la Revolución de la IA?',
    'ai.powered': 'Nuestros agentes de IA están impulsados por tecnologías de vanguardia incluyendo GPT-4, Claude, OLLaMA, y modelos personalizados adaptados a tus necesidades específicas.',

    // Digital Marketing
    'marketing.title': 'Marketing Digital',
    'marketing.subtitle': 'Amplifica el alcance de tu marca e impulsa el crecimiento medible con nuestras soluciones integrales de marketing digital.',
    'marketing.channels': 'Nuestros Canales de Marketing',
    'marketing.why': '¿Por Qué Elegirnos?',
    'marketing.campaigns': 'Campañas Exitosas',
    'marketing.satisfaction': 'Satisfacción del Cliente',
    'marketing.roi': 'Aumento Promedio del ROI',

    // Footer
    'footer.description': 'Transformando negocios a través de soluciones digitales innovadoras. Creamos experiencias que impulsan el crecimiento y el éxito.',
    'footer.services': 'Servicios',
    'footer.contact': 'Contacto',
    'footer.ourTeam': 'Nuestro Equipo',
    'footer.teamDesc': 'Un grupo apasionado de desarrolladores, diseñadores y estrategas dedicados a crear experiencias digitales excepcionales.',
    'footer.joinTeam': 'Únete a Nuestro Equipo',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos de Servicio',
    'footer.rights': 'Todos los derechos reservados.',

    // Features - Responsive Design
    'responsive.title': 'Diseño Responsivo',
    'responsive.description': 'Sitios web hermosos que funcionan perfectamente en todos los dispositivos y tamaños de pantalla.',
    'responsive.detail1': 'Enfoque mobile-first asegurando visualización perfecta en smartphones',
    'responsive.detail2': 'Optimización para tablets con interfaces táctiles intuitivas',
    'responsive.detail3': 'Compatibilidad con escritorio y pantallas grandes',
    'responsive.detail4': 'Diseños fluidos que se adaptan a cualquier tamaño de pantalla',
    'responsive.benefit1': 'Experiencia de usuario mejorada en todos los dispositivos',
    'responsive.benefit2': 'Mejor posicionamiento SEO con indexación mobile-first',
    'responsive.benefit3': 'Tasas de rebote reducidas y mayor engagement',
    'responsive.benefit4': 'Mantenimiento rentable con un solo código base',

    // Features - Lightning Fast
    'lightning.title': 'Súper Rápido',
    'lightning.description': 'Rendimiento optimizado con tecnologías de vanguardia para velocidad extrema.',
    'lightning.detail1': 'División de código para tiempos de carga iniciales más rápidos',
    'lightning.detail2': 'Optimización de imágenes con formatos de nueva generación',
    'lightning.detail3': 'Distribución CDN para latencia mínima',
    'lightning.detail4': 'Estrategias inteligentes de caché para visitas recurrentes',
    'lightning.benefit1': 'Tiempos de carga menores a 1 segundo',
    'lightning.benefit2': 'Puntuaciones PageSpeed de 99+',
    'lightning.benefit3': 'Animaciones suaves a 60fps',
    'lightning.benefit4': 'Cumplimiento 100% de Core Web Vitals',

    // Features - Modern UI/UX
    'modern.title': 'UI/UX Moderno',
    'modern.description': 'Interfaces impresionantes diseñadas con la experiencia del usuario como prioridad.',
    'modern.detail1': 'Estética de diseño limpia y contemporánea',
    'modern.detail2': 'Navegación intuitiva y flujos de usuario',
    'modern.detail3': 'Cumplimiento de estándares de accesibilidad',
    'modern.detail4': 'Micro-interacciones y animaciones atractivas',
    'modern.benefit1': 'Mayor satisfacción y retención de usuarios',
    'modern.benefit2': 'Tasas de conversión más altas',
    'modern.benefit3': 'Imagen de marca profesional',
    'modern.benefit4': 'Ventaja competitiva en el mercado',

    // Features - Secure & Reliable
    'secure.title': 'Seguro y Confiable',
    'secure.description': 'Construido con las mejores prácticas de seguridad y arquitectura robusta.',
    'secure.detail1': 'Encriptación SSL/TLS para toda transmisión de datos',
    'secure.detail2': 'Protección contra los top 10 de OWASP',
    'secure.detail3': 'Auditorías de seguridad y actualizaciones regulares',
    'secure.detail4': 'Garantía de disponibilidad del 99.99%',
    'secure.benefit1': 'Protección contra amenazas cibernéticas',
    'secure.benefit2': 'Privacidad de datos y cumplimiento normativo',
    'secure.benefit3': 'Monitoreo y soporte 24/7',
    'secure.benefit4': 'Garantía de continuidad del negocio',

    // Mobile Features - iOS & Android
    'ios.title': 'iOS y Android',
    'ios.description': 'Aplicaciones nativas y multiplataforma que ofrecen experiencias fluidas en ambas plataformas.',
    'ios.detail1': 'Desarrollo iOS nativo con Swift y SwiftUI',
    'ios.detail2': 'Desarrollo Android nativo con Kotlin y Jetpack Compose',
    'ios.detail3': 'Soluciones multiplataforma usando React Native y Flutter',
    'ios.detail4': 'Optimización de rendimiento para experiencias de usuario fluidas',
    'ios.benefit1': 'Mayor alcance de audiencia en todas las plataformas',
    'ios.benefit2': 'Experiencia de usuario consistente en iOS y Android',
    'ios.benefit3': 'Desarrollo más rápido con códigos base compartidos',
    'ios.benefit4': 'Mantenimiento y actualizaciones más fáciles',

    // Mobile Features - Tablet Optimized
    'tablet.title': 'Optimizado para Tablets',
    'tablet.description': 'Interfaces totalmente optimizadas para tablets con interacciones táctiles intuitivas.',
    'tablet.detail1': 'Diseños adaptativos para varios tamaños de tablets',
    'tablet.detail2': 'Gestos multi-táctiles e interacciones mejoradas',
    'tablet.detail3': 'Soporte para vista dividida y múltiples ventanas',
    'tablet.detail4': 'Optimizado para modos vertical y horizontal',
    'tablet.benefit1': 'Productividad mejorada en pantallas más grandes',
    'tablet.benefit2': 'Mejor experiencia de consumo de contenido',
    'tablet.benefit3': 'Aplicaciones empresariales de nivel profesional',
    'tablet.benefit4': 'Mayor engagement de usuarios en tablets',

    // Mobile Features - Wearables
    'wearables.title': 'Dispositivos Portátiles',
    'wearables.description': 'Amplía el ecosistema de tu aplicación a relojes inteligentes y dispositivos portátiles.',
    'wearables.detail1': 'Integración con Apple Watch y WatchOS',
    'wearables.detail2': 'Soporte para Wear OS de Google',
    'wearables.detail3': 'Capacidades de seguimiento de salud y fitness',
    'wearables.detail4': 'Acciones rápidas y notificaciones',
    'wearables.benefit1': 'Mayor engagement de usuarios a través de wearables',
    'wearables.benefit2': 'Ecosistema de aplicaciones expandido',
    'wearables.benefit3': 'Acceso a datos de salud y fitness',
    'wearables.benefit4': 'Experiencias de usuario innovadoras',

    // Mobile Features - Offline-First
    'offline.title': 'Primero Sin Conexión',
    'offline.description': 'Aplicaciones que funcionan perfectamente incluso sin conexión a Internet.',
    'offline.detail1': 'Almacenamiento local de datos y caché',
    'offline.detail2': 'Sincronización en segundo plano cuando hay conexión',
    'offline.detail3': 'Estrategias de resolución de conflictos',
    'offline.detail4': 'Capacidades de Aplicación Web Progresiva (PWA)',
    'offline.benefit1': 'Experiencia de usuario mejorada sin internet',
    'offline.benefit2': 'Sincronización de datos al volver en línea',
    'offline.benefit3': 'Uso de datos reducido',
    'offline.benefit4': 'Mayor fiabilidad de la aplicación',

    // AI Features - Intelligent Automation
    'automation.title': 'Automatización Inteligente',
    'automation.description': 'Automatiza flujos de trabajo complejos con agentes impulsados por IA que aprenden y se adaptan a las necesidades de tu negocio.',
    'automation.detail1': 'Automatización de flujos de trabajo con toma de decisiones de IA',
    'automation.detail2': 'Optimización de procesos y ganancias de eficiencia',
    'automation.detail3': 'Integración con sistemas empresariales existentes',
    'automation.detail4': 'Aprendizaje y mejora continua',
    'automation.benefit1': 'Costos operativos reducidos',
    'automation.benefit2': 'Finalización de tareas más rápida',
    'automation.benefit3': 'Errores humanos minimizados',
    'automation.benefit4': 'Procesos empresariales escalables',

    // AI Features - Machine Learning
    'ml.title': 'Aprendizaje Automático',
    'ml.description': 'Aprovecha modelos de ML avanzados para extraer información y tomar decisiones basadas en datos.',
    'ml.detail1': 'Desarrollo de modelos ML personalizados',
    'ml.detail2': 'Análisis predictivo y pronósticos',
    'ml.detail3': 'Reconocimiento de patrones y detección de anomalías',
    'ml.detail4': 'Procesamiento de lenguaje natural',
    'ml.benefit1': 'Toma de decisiones basada en datos',
    'ml.benefit2': 'Precisión mejorada con el tiempo',
    'ml.benefit3': 'Perspectivas competitivas del mercado',
    'ml.benefit4': 'Descubrimiento automatizado de patrones',

    // AI Features - Conversational AI
    'conversational.title': 'IA Conversacional',
    'conversational.description': 'Construye chatbots sofisticados y asistentes virtuales que entienden el lenguaje natural.',
    'conversational.detail1': 'Comprensión del lenguaje natural (NLU)',
    'conversational.detail2': 'Conversaciones con contexto',
    'conversational.detail3': 'Soporte multiidioma',
    'conversational.detail4': 'Integración con plataformas de mensajería',
    'conversational.benefit1': 'Soporte al cliente 24/7',
    'conversational.benefit2': 'Costos de soporte reducidos',
    'conversational.benefit3': 'Satisfacción del cliente mejorada',
    'conversational.benefit4': 'Interacciones escalables con clientes',

    // AI Features - Predictive Analytics
    'predictive.title': 'Análisis Predictivo',
    'predictive.description': 'Pronostica tendencias y resultados con modelos de IA entrenados con tus datos.',
    'predictive.detail1': 'Pronóstico de series temporales',
    'predictive.detail2': 'Predicción de comportamiento del cliente',
    'predictive.detail3': 'Evaluación y mitigación de riesgos',
    'predictive.detail4': 'Pronóstico de ventas e ingresos',
    'predictive.benefit1': 'Planificación empresarial proactiva',
    'predictive.benefit2': 'Riesgos empresariales reducidos',
    'predictive.benefit3': 'Asignación de recursos optimizada',
    'predictive.benefit4': 'Decisiones estratégicas mejoradas',

    // Marketing Features - Strategic Planning
    'strategic.title': 'Planificación Estratégica',
    'strategic.description': 'Estrategias de marketing integrales adaptadas a tus objetivos comerciales y público objetivo.',
    'strategic.detail1': 'Investigación de mercado y análisis de competidores',
    'strategic.detail2': 'Identificación de público objetivo',
    'strategic.detail3': 'Planificación de campañas multicanal',
    'strategic.detail4': 'Asignación y optimización de presupuesto',
    'strategic.benefit1': 'Hoja de ruta de marketing clara',
    'strategic.benefit2': 'Alineado con objetivos empresariales',
    'strategic.benefit3': 'Objetivos medibles',
    'strategic.benefit4': 'Ventaja competitiva',

    // Marketing Features - SEO & SEM
    'seo.title': 'SEO y SEM',
    'seo.description': 'Optimiza tu presencia en línea e impulsa tráfico calificado a tus propiedades digitales.',
    'seo.detail1': 'Investigación y optimización de palabras clave',
    'seo.detail2': 'Mejoras técnicas de SEO',
    'seo.detail3': 'Gestión de campañas de pago por clic',
    'seo.detail4': 'Optimización de búsqueda local',
    'seo.benefit1': 'Rankings más altos en motores de búsqueda',
    'seo.benefit2': 'Tráfico orgánico aumentado',
    'seo.benefit3': 'Mejor ROI en gasto publicitario',
    'seo.benefit4': 'Visibilidad en línea mejorada',

    // Marketing Features - Analytics & Insights
    'analytics.title': 'Analítica e Información',
    'analytics.description': 'Información basada en datos para medir el ROI y optimizar tus campañas de marketing.',
    'analytics.detail1': 'Paneles de analítica integrales',
    'analytics.detail2': 'Seguimiento de conversiones y atribución',
    'analytics.detail3': 'Pruebas A/B y experimentación',
    'analytics.detail4': 'Informes personalizados y visualización',
    'analytics.benefit1': 'Toma de decisiones informada',
    'analytics.benefit2': 'Optimización del rendimiento de campañas',
    'analytics.benefit3': 'Medición clara del ROI',
    'analytics.benefit4': 'Mejora continua',

    // Marketing Features - Email Marketing
    'email.title': 'Email Marketing',
    'email.description': 'Involucra a tu audiencia con campañas de email personalizadas que convierten.',
    'email.detail1': 'Segmentación y personalización',
    'email.detail2': 'Secuencias de email automatizadas',
    'email.detail3': 'Pruebas A/B para optimización de emails',
    'email.detail4': 'Seguimiento de rendimiento y analítica',
    'email.benefit1': 'Tasas de apertura y clics más altas',
    'email.benefit2': 'Retención de clientes mejorada',
    'email.benefit3': 'Canal de marketing rentable',
    'email.benefit4': 'Resultados de campaña medibles',

    // Common
    'close': 'Cerrar',
    'learnMore': 'Más Información',
    'keyFeatures': 'Características Clave',
    'benefits': 'Beneficios',
    'requestInfo': 'Solicitar Información',

    // Contact Form
    'contactForm.title': 'Solicitar Información',
    'contactForm.firstName': 'Nombre',
    'contactForm.lastName': 'Apellido',
    'contactForm.email': 'Correo Electrónico',
    'contactForm.phone': 'Teléfono',
    'contactForm.feature': 'Característica de Interés',
    'contactForm.selectFeature': 'Seleccione una característica',
    'contactForm.message': 'Mensaje (Opcional)',
    'contactForm.submit': 'Enviar Solicitud',
    'contactForm.sending': 'Enviando...',
    'contactForm.success': '¡Gracias! Nos pondremos en contacto pronto.',
    'contactForm.error': 'Por favor complete la verificación captcha.',
    'contactForm.required': 'Este campo es requerido',
    'contactForm.captcha': 'Verificación: ¿Cuánto es',

    // Privacy Policy
    'privacy.title': 'Política de Privacidad',
    'privacy.effectiveDate': 'Fecha Efectiva: 1 de Diciembre de 2025',
    'privacy.backHome': 'Volver al Inicio',
    'privacy.section1.title': 'Introducción',
    'privacy.section1.content': 'Autobotec.net ("nosotros," "nos," "nuestro," o "Empresa") respeta tu privacidad y se compromete a proteger tus datos personales. Esta Política de Privacidad explica cómo recopilamos, utilizamos, divulgamos y protegemos tu información cuando visitas nuestro sitio web y utilizas nuestros servicios.',
    'privacy.section2.title': 'Información que Recopilamos',
    'privacy.section2.intro': 'Podemos recopilar información sobre ti de diversas maneras. La información que podemos recopilar en el Sitio incluye:',
    'privacy.section2.personalData': 'Datos Personales',
    'privacy.section2.item1': 'Nombre y dirección de correo electrónico',
    'privacy.section2.item2': 'Número de teléfono',
    'privacy.section2.item3': 'Nombre de la empresa e industria',
    'privacy.section2.item4': 'Dirección postal',
    'privacy.section2.item5': 'Información de pago (procesada de forma segura)',
    'privacy.section2.automatic': 'Recopilación Automática de Datos',
    'privacy.section2.item6': 'Tipo y versión del navegador',
    'privacy.section2.item7': 'Sistema operativo',
    'privacy.section2.item8': 'Páginas visitadas y tiempo invertido en las páginas',
    'privacy.section2.item9': 'Dirección IP',
    'privacy.section2.item10': 'Cookies y tecnologías de seguimiento similares',
    'privacy.section3.title': 'Uso de Tu Información',
    'privacy.section3.intro': 'Tener información precisa sobre ti nos permite proporcionarte una experiencia fluida, eficiente y personalizada. Específicamente, podemos usar la información recopilada sobre ti a través del Sitio para:',
    'privacy.section3.item1': 'Procesar tus transacciones y enviar información relacionada',
    'privacy.section3.item2': 'Enviarte correos electrónicos sobre tu cuenta u orden',
    'privacy.section3.item3': 'Cumplir y administrar compras, pedidos, pagos y otras transacciones relacionadas con el Sitio',
    'privacy.section3.item4': 'Generar un perfil personal sobre ti con fines de investigación de mercado',
    'privacy.section3.item5': 'Aumentar la eficiencia y operación del Sitio',
    'privacy.section3.item6': 'Monitorear y analizar el uso y tendencias para mejorar tu experiencia con el Sitio',
    'privacy.section3.item7': 'Notificarte sobre actualizaciones del Sitio',
    'privacy.section3.item8': 'Ofrecer nuevos productos, servicios o promociones',
    'privacy.section4.title': 'Divulgación de Tu Información',
    'privacy.section4.intro': 'Podemos compartir información que hemos recopilado sobre ti en ciertas situaciones:',
    'privacy.section4.item1': 'Por Ley o para Proteger Derechos: Si creemos que la divulgación de información es necesaria para cumplir con la ley, hacer cumplir nuestras políticas del Sitio, o proteger nuestros derechos o los de otros, propiedad o seguridad.',
    'privacy.section4.item2': 'Proveedores de Servicios Terceros: Podemos compartir tu información con terceros que realizan servicios para nosotros, incluido procesamiento de pagos, análisis de datos, entrega de correos electrónicos y servicio al cliente.',
    'privacy.section4.item3': 'Transferencias Comerciales: Si la Empresa está involucrada en una fusión, adquisición o venta de activos, tu información puede ser transferida como parte de esa transacción.',
    'privacy.section5.title': 'Seguridad de Tu Información',
    'privacy.section5.content': 'Utilizamos medidas de seguridad administrativas, técnicas y físicas para proteger tu información personal. Sin embargo, ningún método de transmisión por Internet o método de almacenamiento electrónico es completamente seguro. Aunque nos esforzamos por usar medios comercialmente aceptables para proteger tu información personal, no podemos garantizar su seguridad absoluta.',
    'privacy.section6.title': 'Contáctanos',
    'privacy.section6.intro': 'Si tienes preguntas o comentarios sobre esta Política de Privacidad, por favor contáctanos en:',
    'privacy.contact.company': 'Autobotec.net',
    'privacy.contact.email': 'Correo: ',
    'privacy.contact.phone': 'Teléfono: ',
    'privacy.contact.address': 'Dirección: 37-09 75 St, Jackson Heights, NY 11372, USA',
    'privacy.lastUpdated': 'Última Actualización: 1 de Diciembre de 2025',

    // Terms of Service
    'terms.title': 'Términos de Servicio',
    'terms.effectiveDate': 'Fecha Efectiva: 1 de Diciembre de 2025',
    'terms.backHome': 'Volver al Inicio',
    'terms.section1.title': 'Acuerdo con los Términos',
    'terms.section1.para1': 'Al acceder y utilizar este sitio web (el "Sitio") y los servicios proporcionados por Autobotec.net ("Empresa," "nosotros," "nos," u "nuestro"), aceptas y aceptas estar vinculado por los términos y condiciones de este acuerdo.',
    'terms.section1.para2': 'Si no estás de acuerdo con lo anterior, por favor no utilices este servicio.',
    'terms.section2.title': 'Licencia de Uso',
    'terms.section2.intro': 'Se otorga permiso para descargar temporalmente una copia de los materiales (información o software) en el Sitio solo para visualización temporal personal y no comercial. Esta es la concesión de una licencia, no una transferencia de propiedad, y bajo esta licencia no puedes:',
    'terms.section2.item1': 'Modificar o copiar los materiales',
    'terms.section2.item2': 'Usar los materiales para cualquier propósito comercial o para cualquier exhibición pública',
    'terms.section2.item3': 'Intentar descomponer, revertir la ingeniería o desensamblar ningún software contenido en el Sitio',
    'terms.section2.item4': 'Eliminar ningún aviso de derechos de autor u otra notación patentada de los materiales',
    'terms.section2.item5': 'Transferir los materiales a otra persona o "reflejar" los materiales en ningún otro servidor',
    'terms.section2.item6': 'Violar leyes o regulaciones aplicables relacionadas con el acceso al Sitio',
    'terms.section2.item7': 'Acceder o buscar el Sitio por cualquier medio que no sea la interfaz públicamente compatible del Sitio',
    'terms.section3.title': 'Descargo de Responsabilidad',
    'terms.section3.para1': 'Los materiales en el Sitio se proporcionan "tal como están." La Empresa no otorga garantías, expresas o implícitas, y por este medio renuncia y niega todas las demás garantías, incluidas, sin limitación, garantías implícitas o condiciones de comercialidad, idoneidad para un propósito particular o no infracción de propiedad intelectual u otra violación de derechos.',
    'terms.section3.para2': 'Además, la Empresa no garantiza ni hace representaciones sobre la precisión, resultados probables o confiabilidad del uso de los materiales en el Sitio o de otro modo relacionados con tales materiales o en ningún sitio vinculado al Sitio.',
    'terms.section4.title': 'Limitaciones',
    'terms.section4.content': 'En ningún caso Autobotec.net o sus proveedores serán responsables por ningún daño (incluidos, sin limitación, daños por pérdida de datos o ganancias, o debido a interrupción comercial) que surja del uso o incapacidad de usar los materiales en el Sitio, incluso si la Empresa o un representante autorizado de la Empresa ha sido notificado oralmente o por escrito de la posibilidad de tal daño.',
    'terms.section5.title': 'Precisión de Materiales',
    'terms.section5.content': 'Los materiales que aparecen en el Sitio podrían incluir errores técnicos, tipográficos o fotográficos. La Empresa no garantiza que ninguno de los materiales en el Sitio sean precisos, completos o actuales. La Empresa puede realizar cambios en los materiales contenidos en el Sitio en cualquier momento sin previo aviso.',
    'terms.section6.title': 'Enlaces',
    'terms.section6.content': 'La Empresa no ha revisado todos los sitios vinculados a su Sitio y no es responsable del contenido de ningún sitio vinculado. La inclusión de cualquier enlace no implica respaldo por parte de la Empresa del sitio. El uso de cualquier sitio web vinculado es bajo tu propio riesgo.',
    'terms.section7.title': 'Modificaciones',
    'terms.section7.content': 'La Empresa puede revisar estos términos de servicio del Sitio en cualquier momento sin previo aviso. Al utilizar este Sitio, aceptas estar vinculado por la versión entonces actual de estos términos de servicio.',
    'terms.section8.title': 'Ley Aplicable',
    'terms.section8.content': 'Estos términos y condiciones se rigen por y se interpretan de conformidad con las leyes de los Estados Unidos de América, y aceptas irrevocablemente la jurisdicción exclusiva de los tribunales en esa ubicación.',
    'terms.section9.title': 'Responsabilidades del Usuario',
    'terms.section9.intro': 'Aceptas no usar el Sitio o su contenido:',
    'terms.section9.item1': 'Para ningún propósito ilegal o para solicitar a otros que cometan actos ilegales',
    'terms.section9.item2': 'Para violar ninguna regulación, regla, ley u ordenanza internacional, federal, provincial o estatal aplicable',
    'terms.section9.item3': 'Para infringir o violar nuestros derechos de propiedad intelectual o los derechos de propiedad intelectual de otros',
    'terms.section9.item4': 'Para acosar, abusar, insultar, dañar, difamar, calumniar, menospreciar, intimidar o discriminar basado en género, orientación sexual, religión, etnia, raza, edad, origen nacional o discapacidad',
    'terms.section9.item5': 'Para enviar información falsa o engañosa',
    'terms.section9.item6': 'Para cargar virus u otro código malicioso u otra forma de comprometer la seguridad del Sitio',
    'terms.section10.title': 'Contáctanos',
    'terms.section10.intro': 'Si tienes preguntas sobre estos Términos de Servicio, por favor contáctanos en:',
    'terms.contact.company': 'Autobotec.net',
    'terms.contact.email': 'Correo: ',
    'terms.contact.phone': 'Teléfono: ',
    'terms.contact.address': 'Dirección: 37-09 75 St, Jackson Heights, NY 11372, USA',
    'terms.lastUpdated': 'Última Actualización: 1 de Diciembre de 2025',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}